#
# Copyright 2015, Noah Kantrowitz
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'spec_helper'

describe PoiseApplicationPython::Resources::Django do
  describe PoiseApplicationPython::Resources::Django::Resource do
    describe '#local_settings' do
      subject { chef_run.application_django('/test').local_settings_content }

      context 'with defaults' do
        recipe(subject: false) do
          application_django '/test'
        end
        it { is_expected.to eq <<-SETTINGS }
# Generated by Chef for application_django[/test]

DEBUG = False

DATABASES = {"default":{}}
SETTINGS
      end # /context with defaults

      context 'with a URL' do
        recipe(subject: false) do
          application_django '/test' do
            database 'postgres://myuser@dbhost/myapp'
          end
        end
        it { is_expected.to eq <<-SETTINGS }
# Generated by Chef for application_django[/test]

DEBUG = False

DATABASES = {"default":{"URL":"postgres://myuser@dbhost/myapp","ENGINE":"django.db.backends.postgresql_psycopg2","NAME":"myapp","USER":"myuser","HOST":"dbhost"}}
SETTINGS
      end # /context with a URL

      context 'with an options block' do
        recipe(subject: false) do
          application_django '/test' do
            database do
              engine 'postgres'
              name 'myapp'
              user 'myuser'
              host 'dbhost'
            end
          end
        end
        it { is_expected.to eq <<-SETTINGS }
# Generated by Chef for application_django[/test]

DEBUG = False

DATABASES = {"default":{"ENGINE":"django.db.backends.postgresql_psycopg2","NAME":"myapp","USER":"myuser","HOST":"dbhost"}}
SETTINGS
      end # /context with an options block

      context 'with debug mode' do
        recipe(subject: false) do
          application_django '/test' do
            debug true
          end
        end
        it { is_expected.to eq <<-SETTINGS }
# Generated by Chef for application_django[/test]

DEBUG = True

DATABASES = {"default":{}}
SETTINGS
      end # /context with debug mode
    end # /describe #local_settings
  end # /describe PoiseApplicationPython::Resources::Django::Resource
end
